last try

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,13 +35,13 @@ jobs:
         # continue-on-error: false
 
       - name: Check if test failed
-          if: always()
-          run: |
-            if [ $? -ne 0 ]
-            then
-              echo "Tests failed"
-              --exit
-            fi
+        if: always()
+        run: |
+          if [ $? -ne 0 ]
+          then
+            echo "Tests failed"
+            --exit
+          fi
       
       - name: Archieve Cucumber Reports
         uses: actions/upload-artifact@v3
